trigger:
  branches:
    include:
      - main  # or your default branch name

variables:
  dockerHubUsername: haridoc00
  imageName: flask-app

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - script: |
        docker build -t $(dockerHubUsername)/$(imageName):latest .
        echo "$(DOCKER_HUB_PASSWORD)" | docker login -u $(dockerHubUsername) --password-stdin
        docker push $(dockerHubUsername)/$(imageName):latest
      displayName: 'Build and Push Docker Image'

- stage: Deploy
  dependsOn: BuildAndPush
  jobs:
  - deployment: DeployWebApp
    environment: 'production'
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: '<your-service-connection-name>'
              appName: 'my-app-prod-123'
              imageName: 'haridoc00/flask-app:latest'
